FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# ionic

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/login]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "username": "teste",
            "password": "teste"
        }

+ Response 200 (application/json)

    + Body

            {
                "name": "Gerson Lange",
                "token": "asdfasdfasdfasdfa"
            }

## Questions Collection [/dados]

### Create a New Question [GET]
+ Response 200 (application/json)

    + Body

            {
                "dados": [
                    {
                        "id": 1,
                        "nome": "Joao",
                        "sobrenome": "da Silva",
                        "imagem": "https://s3.amazonaws.com/igd-wp-uploads-pluginaws/wp-content/uploads/2016/05/30105213/Qual-e%CC%81-o-Perfil-do-Empreendedor.jpg",
                        "texto": "Meu texto de curriculum é bla bla bla"
                    },
                    {
                        "id": 2,
                        "nome": "Maia",
                        "sobrenome": "Paulo",
                        "imagem": "https://cptstatic.s3.amazonaws.com/imagens/enviadas/materias/materia11094/2negociacao-cursos-cpt.jpg",
                        "texto": "Meu texto de curriculum é bla bla bla"
                    },
                    {
                        "id": 3,
                        "nome": "Helio",
                        "sobrenome": "Rosa",
                        "imagem": "https://cptstatic.s3.amazonaws.com/imagens/enviadas/materias/materia11596/etiqueta2-cursos-cpt.jpg",
                        "texto": "Meu texto de curriculum é bla bla bla"
                    },
                    {
                        "id": 4,
                        "nome": "Henrique",
                        "sobrenome": "Sobrenome",
                        "imagem": "https://s3.amazonaws.com/igd-wp-uploads-pluginaws/wp-content/uploads/2016/05/30105213/Qual-e%CC%81-o-Perfil-do-Empreendedor.jpg",
                        "texto": "Meu texto de curriculum é bla bla bla"
                    }
                ]
            }

## Questions Collection [/dados/1]

### Create a New Question [GET]
+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "nome": "Joao",
                "sobrenome": "da Silva",
                "imagem": "https://s3.amazonaws.com/igd-wp-uploads-pluginaws/wp-content/uploads/2016/05/30105213/Qual-e%CC%81-o-Perfil-do-Empreendedor.jpg",
                "texto": "Meu texto de curriculum é bla bla bla"
            }

## Questions Collection [/dados/2]

### Create a New Question [GET]
+ Response 200 (application/json)

    + Body

            {
                "id": 2,
                "nome": "Maia",
                "sobrenome": "Paulo",
                "imagem": "https://cptstatic.s3.amazonaws.com/imagens/enviadas/materias/materia11094/2negociacao-cursos-cpt.jpg",
                "texto": "Meu texto de curriculum é bla bla bla"
            }

## Questions Collection [/dados/3]

### Create a New Question [GET]
+ Response 200 (application/json)

    + Body

            {
                "id": 3,
                "nome": "Helio",
                "sobrenome": "Rosa",
                "imagem": "https://cptstatic.s3.amazonaws.com/imagens/enviadas/materias/materia11596/etiqueta2-cursos-cpt.jpg",
                "texto": "Meu texto de curriculum é bla bla bla"
            }
            

## Questions Collection [/dados/4]

### Create a New Question [GET]
+ Response 200 (application/json)

    + Body

            {
                "id": 4,
                "nome": "Henrique",
                "sobrenome": "Sobrenome",
                "imagem": "https://s3.amazonaws.com/igd-wp-uploads-pluginaws/wp-content/uploads/2016/05/30105213/Qual-e%CC%81-o-Perfil-do-Empreendedor.jpg",
                "texto": "Meu texto de curriculum é bla bla bla"
            }